### ISSUE TITLE
.wrap width

### ISSUE THREAD

**Issue by mttymtt** [devinhalladay/devinhalladay.com#3]
I notice that you have a max-width set for the wrap class, but only have a defined width percentage when it's scaled down. If you just keep the width set at 90% with the max-width still set then it should fix the issue with your Read Next sections on Journal posts.

BEFORE
![devin_001](https://cloud.githubusercontent.com/assets/10723688/5917378/f80c95b8-a5e9-11e4-988d-814a966bd5e8.jpg)

AFTER
![devin_002](https://cloud.githubusercontent.com/assets/10723688/5917377/f80771aa-a5e9-11e4-9c42-d0ec9136b594.jpg)

**Comment by devinhalladay** [comment]
What browser are you using? I've tested this in Chrome (stable and dev channels) and in Safari and I haven't been able to reproduce what's shown in your screenshot.

**Comment by mttymtt** [comment]
I tested it in Chrome originally, but also tested Firefox, and Safari using

.wrap {
padding: 0 2%;
width: 90%;
max-width: 1200px;
margin: auto;
}

In Safari it was already full width like the screenshot above, but setting a width didn't affect anything else on the page.

**Comment by devinhalladay** [comment]
:shipit: :+1: All fixed. Thanks @mttymtt!

**Comment by devinhalladay** [comment]
@mttymtt also I saw your tweet about creating a GitHub account a week or so back; if you ever need some help finding your way around or getting started with Git, feel free to ping me!
